defaults: &defaults
  docker:
    - image: circleci/node:10.9.0
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    branches:
      only: develop
    steps:
      - checkout
      - run: git clone https://github.com/hpcslag/hexo-theme-morgan.git themes/tocas-ui-morgan
      - run: npm install hexo-cli
      - run: npm install
      - run: npx hexo deploy